---

- name: Install f.lux
  homebrew_cask: name=flux state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir={{ homebrew_cask_appdir }}
  notify: brew cask cleanup

# TODO: Make idempotent
- name: Set location
  command: defaults write org.herf.Flux {{ item }}
  with_items:
    - location -string "{{ flux_location }}"
    - locationTextField -string {{ flux_locationTextField }}
  changed_when: false
  notify:
    - killall Flux

- name: Set colour temperatures
  osx_defaults:
    domain: org.herf.Flux
    key: "{{ item.key }}"
    type: int
    value: "{{ item.value }}"
  with_items:
    - { key: 'lateColorTemp', value: "{{ flux_lateColorTemp }}" }
    - { key: 'nightColorTemp', value: "{{ flux_nightColorTemp }}" }
  notify:
    - killall Flux
